version: "3.0"
services:
  web:
    # TODO: image, ports and redis dependency
    image: "damek1010/io-lab-docker-ci-public"
    ports:
      - "8080:5000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis:6.0-rc3
    volumes:
      - "redis-data:/data"
    # TODO: persistence for redis. You need to persist /data directory.
volumes:
  redis-data:
